version: '3'
services:
  db:
    image: mysql
    restart: 'no'
    platform: linux/x86_64
    container_name: db
    ports:
      - "3306:3306"
    expose:
      - '3306'
#    command:
#        - /bin/bash
#        - -c
#        - |
#          sleep 10
#      -  mkdir -p /data/swap-application/
#          - --init-file /data/swap-application/init.sql
    environment:
#      - MYSQL_USER=root
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_application
    volumes:
      - ./mysql-post/init.sql:/data/swap-application/init.sql
      - /usr/local/mysql-post-8.0.28-macos11-arm64/bin/mysqld:/var/lib/mysql-post
      - /tmp/:/var/run/mysqld

  web:
    build: .
    container_name: web
    command:
        - /bin/bash
        - -c
        - |
          sleep 30
          python manage.py makemigrations
          sleep 10
          python manage.py migrate
          sleep 10
          python manage.py runserver 0.0.0.0:8080
          sleep 10
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/mysql-post-8.0.28-macos11-arm64/bin/mysqld:/run/mysqld
      - /tmp/:/run/mysqld
    depends_on:
      - db
    links:
      - db
