pipeline {
    agent any
    
    environment {
    DC_PATH = "$WORKSPACE/SWAP/django_swap"
  }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
/*                sh "git clone -b "main" https://github.com/David-Melamed/SWAP-Web.git"
                  sh "mkdir -p ~/SWAP-APP && cp . ~/SWAP-APP/"*/
                script {
                    def buildNumber = env.BUILD_NUMBER
                    def workspace = env.WORKSPACE
                    def buildUrl = env.BUILD_URL

                    println("Build Number " + buildNumber)
                    println("Active Workspace - " + workspace)
                    println("Build URL " + buildUrl)
                    }

//                 sh "mkdir -p ~/code/"
//                 sh "cp -Rf $WORKSPACE/SWAP/* ~/code/"

                echo 'The code has been successfully pulled - testd'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml down"
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml build"
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml up -d"

            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh "docker ps"
            }
        }
    }
}
