pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
/*                sh "git clone -b "main" https://github.com/David-Melamed/SWAP-Web.git"*/
                  sh "mkdir -p ~/SWAP-APP && cp . ~/SWAP-APP/"
                echo 'Pulled the code'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
