pipeline {
    agent any
    
    environment {
    DC_PATH = "$WORKSPACE/SWAP/django_swap"
    AWS_DEFAULT_REGION = "us-east-1"
  }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    def buildNumber = env.BUILD_NUMBER
                    def workspace = env.WORKSPACE
                    def buildUrl = env.BUILD_URL

                    println("Build Number " + buildNumber)
                    println("Active Workspace - " + workspace)
                    println("Build URL " + buildUrl)
                    }


                echo 'The code has been successfully pulled - testd'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml down"
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml build"
		        sh "docker-compose -f ${DC_PATH}/docker-compose.yml up -d"

            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
               sh "docker ps"

               withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'swap-ec2-creds',
               secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                    aws --version
                    aws ec2 describe-instances
                    '''

                    }

            }
        }
    }
}
