version: '3'
services:
  db:
    image: mysql
    restart: 'no'
    platform: linux/x86_64
    container_name: db
    ports:
      - "3307:3306"
    expose:
      - '3307'
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /var/run/mysqld
      - ./mysql/mysql-post-commands.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  web:
    build: .
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: "django_main.settings"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    command:
        - /bin/bash
        - -c
        - |
          sleep 30
          python manage.py makemigrations
          sleep 10
          python manage.py migrate
          sleep 10
          python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - /run/mysqld/
      - /var/lib/mysql/
    depends_on:
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge