# Generated by Django 3.2.11 on 2022-02-08 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(default='https://bootdey.com/img/Content/avatar/avatar7.png', upload_to='')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='all_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(default='SlugDefaultValue')),
                ('description', models.CharField(max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
