# Generated by Django 3.2.11 on 2022-02-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220208_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_items',
            name='slug',
            field=models.SlugField(default='wp7V9nyw3SDGysJSai2m'),
        ),
    ]
