# Generated by Django 4.0.4 on 2022-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_all_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_items',
            name='slug',
            field=models.SlugField(default='h2ajqZ60SUxIGmogB93k'),
        ),
    ]
