# Generated by Django 4.0.4 on 2022-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_all_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_items',
            name='slug',
            field=models.SlugField(default='gyfDyA9H42CWyIsO4cdw'),
        ),
    ]
