apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql
        name: mysql
        resources: {}
status: {}
